In [1]:
import pandas as pd
import os

print("Day 17: Final Data Quality Report")
print("Project folder:", os.getcwd())

Day 17: Final Data Quality Report
Project folder: C:\Users\asd\Desktop\open-source-data-quality-analyzer

In [2]:
comparison = pd.read_csv("day15_quality_score_comparison.csv")

print("Quality score report loaded successfully!")
display(comparison)

Quality score report loaded successfully!

                File Name  Quality Score (%)
0  sales_cleaned_day3.csv              100.0
1      sample_sales_2.csv               50.0

In [3]:
final_report = comparison.copy()

final_report["Result"] = final_report["Quality Score (%)"].apply(
    lambda score: "Excellent" if score >= 90
    else "Good" if score >= 70
    else "Needs Improvement"
)

final_report["Report Date"] = pd.Timestamp.today().strftime("%Y-%m-%d")

display(final_report)

                File Name  Quality Score (%)             Result Report Date
0  sales_cleaned_day3.csv              100.0          Excellent  2026-10-16
1      sample_sales_2.csv               50.0  Needs Improvement  2026-10-16

In [4]:

final_report.to_csv("day17_final_quality_report.csv", index=False)

print("Final report saved successfully!")
print("File name: day17_final_quality_report.csv")

Final report saved successfully!
File name: day17_final_quality_report.csv