In [1]:
import pandas as pd
import os

print("Day 26: Automatic Data Cleaning")
print("Project folder:", os.getcwd())

Day 26: Automatic Data Cleaning
Project folder: C:\Users\asd\Desktop\open-source-data-quality-analyzer

In [2]:
df = pd.read_csv("sample_sales_2.csv")

print("Dataset loaded successfully!")
print("Rows before cleaning:", len(df))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

display(df)

Dataset loaded successfully!
Rows before cleaning: 4
Missing values: 1
Duplicate rows: 0

   order_id product  quantity  price    city
0       201   Phone         2  15000  Jaipur
1       202  Tablet         1  25000   Delhi
2       203     NaN         3    500  Mumbai
3       204  Laptop         0  40000  Jaipur

In [3]:
# Remove duplicate rows
df_cleaned = df.drop_duplicates().copy()

# Fill missing product and city values
df_cleaned["product"] = df_cleaned["product"].fillna("Unknown")
df_cleaned["city"] = df_cleaned["city"].fillna("Unknown")

# Fill missing quantity with median
df_cleaned["quantity"] = df_cleaned["quantity"].fillna(
    df_cleaned["quantity"].median()
)

# Remove records with zero or negative quantity/price
df_cleaned = df_cleaned[
    (df_cleaned["quantity"] > 0) &
    (df_cleaned["price"] > 0)
].copy()

print("Automatic cleaning completed!")
print("Rows before cleaning:", len(df))
print("Rows after cleaning:", len(df_cleaned))

display(df_cleaned)

Automatic cleaning completed!
Rows before cleaning: 4
Rows after cleaning: 3

   order_id  product  quantity  price    city
0       201    Phone         2  15000  Jaipur
1       202   Tablet         1  25000   Delhi
2       203  Unknown         3    500  Mumbai

In [4]:
df_cleaned.to_csv("day26_cleaned_sales.csv", index=False)

print("Cleaned dataset saved successfully!")
print("File name: day26_cleaned_sales.csv")
print("Total records saved:", len(df_cleaned))

Cleaned dataset saved successfully!
File name: day26_cleaned_sales.csv
Total records saved: 3

In [5]:
cleaned_df = pd.read_csv("day26_cleaned_sales.csv")

print("Cleaned file loaded successfully!")
print("Total records:", len(cleaned_df))
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())
print("Invalid quantities:", (cleaned_df["quantity"] <= 0).sum())
print("Invalid prices:", (cleaned_df["price"] <= 0).sum())

display(cleaned_df)

Cleaned file loaded successfully!
Total records: 3
Missing values: 0
Duplicate rows: 0
Invalid quantities: 0
Invalid prices: 0

   order_id  product  quantity  price    city
0       201    Phone         2  15000  Jaipur
1       202   Tablet         1  25000   Delhi
2       203  Unknown         3    500  Mumbai

In [6]:
cleaning_report = pd.DataFrame({
    "Metric": [
        "Rows Before Cleaning",
        "Rows After Cleaning",
        "Rows Removed",
        "Missing Values Remaining",
        "Duplicate Rows Remaining",
        "Invalid Quantities Remaining",
        "Invalid Prices Remaining"
    ],
    "Result": [
        len(df),
        len(cleaned_df),
        len(df) - len(cleaned_df),
        int(cleaned_df.isnull().sum().sum()),
        int(cleaned_df.duplicated().sum()),
        int((cleaned_df["quantity"] <= 0).sum()),
        int((cleaned_df["price"] <= 0).sum())
    ]
})

display(cleaning_report)

                         Metric  Result
0          Rows Before Cleaning       4
1           Rows After Cleaning       3
2                  Rows Removed       1
3      Missing Values Remaining       0
4      Duplicate Rows Remaining       0
5  Invalid Quantities Remaining       0
6      Invalid Prices Remaining       0

In [7]:

cleaning_report = pd.DataFrame({
    "Metric": [
        "Rows Before Cleaning",
        "Rows After Cleaning",
        "Rows Removed",
        "Missing Values Remaining",
        "Duplicate Rows Remaining",
        "Invalid Quantities Remaining",
        "Invalid Prices Remaining"
    ],
    "Result": [
        len(df),
        len(cleaned_df),
        len(df) - len(cleaned_df),
        int(cleaned_df.isnull().sum().sum()),
        int(cleaned_df.duplicated().sum()),
        int((cleaned_df["quantity"] <= 0).sum()),
        int((cleaned_df["price"] <= 0).sum())
    ]
})

display(cleaning_report)

                         Metric  Result
0          Rows Before Cleaning       4
1           Rows After Cleaning       3
2                  Rows Removed       1
3      Missing Values Remaining       0
4      Duplicate Rows Remaining       0
5  Invalid Quantities Remaining       0
6      Invalid Prices Remaining       0

In [8]:

cleaning_report.to_csv(
    "day26_cleaning_summary_report.csv",
    index=False
)

print("Cleaning summary report saved successfully!")
print("File: day26_cleaning_summary_report.csv")

Cleaning summary report saved successfully!
File: day26_cleaning_summary_report.csv

In [9]:

import os
import pandas as pd

files_to_check = [
    "day26_cleaned_sales.csv",
    "day26_cleaning_summary_report.csv"
]

for file in files_to_check:
    if os.path.exists(file):
        print(f"✅ {file} — Created successfully")
    else:
        print(f"❌ {file} — File not found")

print("\nFinal Cleaning Summary:")
display(pd.read_csv("day26_cleaning_summary_report.csv"))

✅ day26_cleaned_sales.csv — Created successfully
✅ day26_cleaning_summary_report.csv — Created successfully

Final Cleaning Summary:

                         Metric  Result
0          Rows Before Cleaning       4
1           Rows After Cleaning       3
2                  Rows Removed       1
3      Missing Values Remaining       0
4      Duplicate Rows Remaining       0
5  Invalid Quantities Remaining       0
6      Invalid Prices Remaining       0